# fly.toml file generated for frensing-phonebook-backend on 2023-04-16T12:43:45+03:00

app = "frensing-phonebook-backend"
primary_region = "arn"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
